services:
  - type: web
    name: bio-test-tg
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: CHANNEL_USERNAME
        sync: false
      - key: CHANNEL_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_AUTH_TOKEN
        sync: false
      - key: DEV_AUTH
        value: "0"
